.PHONY: clean huffman levelorder pointerqueue traversalconvert listconcat postorder preorder

huffman: huffman.py
		chmod u+x huffman.py
		python huffman.py

levelorder: levelorder.py
	chmod u+x levelorder.py
	python levelorder.py

pointerqueue: pointerqueue.py
	chmod u+x pointerqueue.py
	python pointerqueue.py

traversalconvert: traversalconvert.py
	chmod u+x traversalconvert.py
	python traversalconvert.py

listconcat: listconcat.py
	chmod u+x listconcat.py
	python listconcat.py

postorder: postorder.py
	chmod u+x postorder.py
	python postorder.py

preorder: preorder.py
	chmod u+x preorder.py
	python preorder.py

clean:
	@\rm -f *.pyc
