.PHONY : clean time arraylist pointerlist arraystack pointerstack

time: timing.py
	chmod u+x timing.py
	python timing.py

arraylist: arraylisttest.py
	chmod u+x arraylisttest.py
	python arraylisttest.py

pointerlist: pointerlisttest.py
	chmod u+x pointerlisttest.py
	python pointerlisttest.py

arraystack: arraystacktest.py
	chmod u+x arraystacktest.py
	python arraystacktest.py

pointerstack: pointerstacktest.py
	chmod u+x pointerstacktest.py
	python pointerstacktest.py

clean:
	@\rm -f *.pyc
