PYTHON = python
VIEWER = less

.PYONY: run view

run : problem1
		#chmod u+x problem1
		$(PYTHON) problem1 
run : problem2
		#chmod u+x problem2
		$(PYTHON) problem2
run : problem3
		#chmod u+x problem3
		$(PYTHON) problem3
view : problem1
		- $(VIEWER) problem1
		- $(VIEWER) problem2

