
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "\x80M\xa35\xe1\xa1\x91\x0e\xf3\xe75\xe7'\x03]u"
    
_lr_action_items = {'RPAREN':([1,3,5,6,8,11,12,13,14,],[-2,-7,-6,-4,12,-1,-8,-5,-3,]),'POWER':([3,5,12,],[-7,9,-8,]),'NUMBER':([0,4,7,9,10,],[3,3,3,3,3,]),'TIMES':([3,5,6,12,13,],[-7,-6,10,-8,-5,]),'PLUS':([1,3,5,6,12,13,14,],[7,-7,-6,-4,-8,-5,-3,]),'LPAREN':([0,4,7,9,10,],[4,4,4,4,4,]),'$end':([1,2,3,5,6,11,12,13,14,],[-2,0,-7,-6,-4,-1,-8,-5,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,7,],[2,8,11,]),'term':([0,4,7,10,],[1,1,1,14,]),'factor':([0,4,7,9,10,],[5,5,5,5,5,]),'pow':([0,4,7,9,10,],[6,6,6,13,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> term PLUS expr','expr',3,'p_expr_a','math_example.py',67),
  ('expr -> term','expr',1,'p_expr_b','math_example.py',71),
  ('term -> pow TIMES term','term',3,'p_term_a','math_example.py',75),
  ('term -> pow','term',1,'p_term_b','math_example.py',78),
  ('pow -> factor POWER pow','pow',3,'p_pow_a','math_example.py',81),
  ('pow -> factor','pow',1,'p_pow_b','math_example.py',84),
  ('factor -> NUMBER','factor',1,'p_factor_a','math_example.py',88),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_b','math_example.py',91),
]
